# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node CI for Boostlet 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  Test-New-Boostlet-Dist:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
    - run: npx parcel build
    - run: npm run dev &
    - run: npm run test
    - name: Check if all tests passed
      run: |
        if [ "$allTestsPassed" = "false" ]; then
          echo "Some tests failed. Check workflow summary to learn more."
          exit 1
        fi
      env:
          allTestsPassed: ${{ env.allTestsPassed }}
    - uses: actions/upload-artifact@v4
      with:
        name: Screenshots-From-Testing
        path: ./tests/scripts/images/ # or path/to/artifact
  
  Check-for-failure:
    needs: Test-New-Boostlet-Dist
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Comment current pull request
        uses: alawiii521/current-pr-comment@v1.0
        with:
          comment: "
              ## :x: Test Failed :x:
              Hi there! It looks like the tests did not pass successfully. :worried:

              **Please check the ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} for more details.** "
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}